### PR TITLE
Create Insomnia integration

### PR DESCRIPTION
**Pull request by dcatipon**

### CODE REVIEW

**Comment by dcatipon** [comment]
[Create the Insomia integration](https://trello.com/c/HNZgQ3SX/7-create-the-insomia-integration)

**Comment by luiztiago** [comment]
Looks great :shipit: 

Can you give me access on your Trello? 
`This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.`

**Comment by dcatipon** [comment]
@luiztiago It's great because the hash logic came from your electron project. lol 🤣

**Comment by luiztiago** [comment]
Hahahahhaa 😍

**Comment by dcatipon** [comment]
[Tweak implementation to use data from form variables](https://trello.com/c/dgG43KkH/10-tweak-implementation-to-use-data-from-form-variables)

**Comment by luiztiago** [comment]
Looks better :shipit:

**Pull request merged**
